"""Initial migration

Revision ID: 05d8b322025a
Revises: d6efdceb2991
Create Date: 2024-09-11 13:18:12.625495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05d8b322025a'
down_revision = 'd6efdceb2991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_call_count', sa.Integer(), nullable=True))
        batch_op.drop_column('subscription_plan')
        batch_op.drop_column('api_calls_today')
        batch_op.drop_column('subscription_end_date')
        batch_op.drop_column('last_api_call_reset')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_api_call_reset', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('api_calls_today', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_plan', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('api_call_count')

    # ### end Alembic commands ###
