"""Add FineTuneJob model

Revision ID: 8b8e04b0c606
Revises: 
Create Date: 2024-09-10 18:31:24.385208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8e04b0c606'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fine_tune_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('training_file', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('api_call_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_call_count', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('fine_tune_job')
    # ### end Alembic commands ###
